# System Setup

For the current tutorial we'll be using **R**. R is a statistical programming language commonly used in bioinformatics.

R can be run from the command line but here we'll be using an interface - refered to as an integrated development environment (IDE) - called **RStudio**.

Before we start we need to make sure R, RStudio and some extra packages within R are installed. Follow the installation instructions for your operating system below to setup everything you need for the tutorial. 

### R 

  * For Mac OS X: 

    Go to [CRAN](https://cran.r-project.org/bin/macosx/) and download the instalation package appropriate for your OS and simply follow the instructions.

  * For Windows:

    Go [here](https://cloud.r-project.org/) -> 'Download R for Windows' -> 'base' -> 'Download R3.4.1 for Windows'. The installer will take you through setup. 

  * For Ubuntu:

    Through the software center - just search for r-base and install.

    At the command line:
```{bash, eval=FALSE, message=FALSE, warning=FALSE}
  sudo apt-get update
  sudo apt-get install r-base
```

### RStudio

To get RStudio simply [go here](https://www.rstudio.com/products/rstudio/download), download the installer appropriate for your system and follow the instructions.

### Download Course Materials

I've created a small set of sample data to use in the analysis that we need to download - go to my [github](https://github.com/MERobinson/MERobinson.github.io) -> click the **Clone or download** button in the top right -> select **Download ZIP**. Once finished downloading unzip it somewhere sensible. Done.
